/**
 * Avatar
 * ----------------
 * A stylized cartoon avatar of you, generated by DiceBear (free, no
 * signup, no image upload needed): https://www.dicebear.com
 *
 * To customize the look:
 * 1. Go to https://www.dicebear.com/playground/
 * 2. Pick a style you like (try "notionists", "avataaars", or "micah"
 *    for a friendly illustrated-person look)
 * 3. Adjust hair, skin tone, accessories etc. in the playground
 * 4. Copy the "seed" value and style name shown, and update the
 *    STYLE and SEED constants below
 *
 * If you'd rather use a custom-drawn avatar (e.g. commissioned or
 * made by a friend), just drop the image in /public/avatar.png and
 * replace the <img> src below with "/avatar.png".
 */

const STYLE = "notionists"; // try: notionists, avataaars, micah, adventurer
const SEED = "mohit-tiwari"; // any text — same seed always gives the same avatar

export default function Avatar() {
  const src = `https://api.dicebear.com/9.x/${STYLE}/svg?seed=${encodeURIComponent(
    SEED
  )}&backgroundColor=1e1712`;

  return (
    <div className="relative h-20 w-20 shrink-0 sm:h-24 sm:w-24">
      <div className="absolute inset-0 rounded-full bg-accent/20 blur-xl" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt="Illustrated avatar"
        className="relative h-full w-full rounded-full border-2 border-gold object-cover"
      />
    </div>
  );
}
